version: "3.9"

services:
  api:
    build: ./backend
    environment:
      - FRONTEND_ORIGIN=http://localhost
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"

  web:
    build: ./frontend
    depends_on:
      - api
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"